### ISSUE TITLE
Error: Failed to install 'ieugwasr' from GitHub

### ISSUE THREAD

**Issue by nsdeboer** [MRCIEU/ieugwasr#8]
I tried to install 'ieugwasr' using the following code in R Studio:

devtools::install_github("mrcieu/ieugwasr")

After having specified that I want to update all associated packages, I receive the following warning message:

package ‘rlang’ successfully unpacked and MD5 sums checked
Error: Failed to install 'ieugwasr' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘rlang’

I have tried to run the code with R version 3.6.1 and with version 3.6.3, but in both cases I receive the same error.

Do you know how I could solve this error? Thanks in advance!

**Comment by remlapmot** [comment]
There are some helpful comments about this error in R [here](https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi).

If those ideas don't work for you:

- What operating system are you on?
- Do you have Admin rights on this computer?

I have have had a similar error on Windows when some packages were installed with Admin rights *'For all users'* and then updating those packages failed when R/RStudio was launched without Admin rights. To launch R/RStudio with Admin rights Shift+Right click the shortcut to the executable and select *Run as administrator*. 
![launch-as-admin](https://user-images.githubusercontent.com/3777473/75765908-2fd10280-5d38-11ea-858a-88e8d97e1674.png)
Then retry the install.

Note it would have been more helpful to compare 3.5.3 and 3.6.3 because R minor versions use the same library folder (i.e. 3.6.1 and 3.6.3 will use the same library folder).

**Comment by nsdeboer** [comment]
Thank you for your help, I managed to install the package!
